### ISSUE TITLE
save game folder

### ISSUE THREAD

**Issue by tunip3** [tuxuser/py-durango-tools#3]
i was wondering where i would find the save game folder on the internal hdd or is there another dump method

**Comment by tuxuser** [comment]
You should have acquired that info before you started with this tool. There is currently no way to get to the savegame files. There was one.. Some time ago.

**Comment by tunip3** [comment]
Then why put it in HDD tools and why not say that in the readme

**Comment by tuxuser** [comment]
A) The savegames are ON the HDD - But, in an encrypted (currently non-decryptable) container (aka. Xvd) aka ConnectedStorage

B) This repo is actually not targeted towards the enduser, its ment for developers and serves AS a base of information. Basically for a time the Xbox one is "opened" - if that ever happens. Hence no note in the README.

**Comment by tunip3** [comment]
ok thanks also xvd is decryptable so long as it is dev signed
